### GET USERS -> returns all users
GET https://joselriascos-exercise-tracker.netlify.app/api/users

### POST USER -> add a new user or returns it if exists
POST https://joselriascos-exercise-tracker.netlify.app/api/users
Content-Type: application/json

{
    "username": "Camilo"
}

### POST USER -> add a new user or returns it if exists
POST https://joselriascos-exercise-tracker.netlify.app/api/users
Content-Type: application/json

{
    "username": "Jose"
}

### GET USERS -> returns all users
GET https://joselriascos-exercise-tracker.netlify.app/api/users

### POST EXERCISE
POST https://joselriascos-exercise-tracker.netlify.app/api/users/d7a9ea2b-d248-4fbc-b3d9-aa9747fcf3f1/exercises
Content-Type: application/json

{
    "description": "Jumping Jacks",
    "duration": 2
}

### POST EXERCISE user non existing
POST https://joselriascos-exercise-tracker.netlify.app/api/users/a/exercises
Content-Type: application/json

{
    "description": "Jumping Jacks",
    "duration": 2
}

### POST EXERCISE with date
POST https://joselriascos-exercise-tracker.netlify.app/api/users/d7a9ea2b-d248-4fbc-b3d9-aa9747fcf3f1/exercises
Content-Type: application/json

{
    "description": "Jumping Jacks",
    "duration": 8,
    "date": "2025-08-28"
}

### POST EXERCISE with date
POST https://joselriascos-exercise-tracker.netlify.app/api/users/d7a9ea2b-d248-4fbc-b3d9-aa9747fcf3f1/exercises
Content-Type: application/json

{
    "description": "Soccer",
    "duration": 90,
    "date": "2025-08-26"
}

### POST EXERCISE with date
POST https://joselriascos-exercise-tracker.netlify.app/api/users/d7a9ea2b-d248-4fbc-b3d9-aa9747fcf3f1/exercises
Content-Type: application/json

{
    "description": "Basketball",
    "duration": 60,
    "date": "2023-08-26"
}

### GET ALL LOGS for d7a9ea2b-d248-4fbc-b3d9-aa9747fcf3f1
GET https://joselriascos-exercise-tracker.netlify.app/api/users/d7a9ea2b-d248-4fbc-b3d9-aa9747fcf3f1/logs

### GET 2 LOGS for d7a9ea2b-d248-4fbc-b3d9-aa9747fcf3f1 from 01-01-2025 to 31-12-2025
GET https://joselriascos-exercise-tracker.netlify.app/api/users/d7a9ea2b-d248-4fbc-b3d9-aa9747fcf3f1/logs?from=2025-01-01&to=2025-12-31&limit=0
