### Add a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "Jose"
}

### Add a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "Daniel"
}

### Add a user
POST http://localhost:3000/api/users
Content-Type: application/x-www-form-urlencoded

username=Diana

### Add a user
POST http://localhost:3000/api/users
Content-Type: application/x-www-form-urlencoded

username=Luis

### Add a user
POST http://localhost:3000/api/users
Content-Type: application/x-www-form-urlencoded

username=Carlos

### Add exercise
POST http://localhost:3000/api/users/68f445a8854f8ac2882fe422/exercises
Content-Type: application/json

{
    "description": "algo",
    "duration": 5
}

### Add exercise with date
POST http://localhost:3000/api/users/68f445a8854f8ac2882fe422/exercises
Content-Type: application/json

{
    "description": "otra cosa",
    "duration": 15,
    "date": "2025-08-28"
}

### Add user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "Diego"
}

### Add user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "Valen"
}

### Get users
GET http://localhost:3000/api/users

### Get logs
GET http://localhost:3000/api/users/68f445a8854f8ac2882fe422/logs

### Get logs with query
GET http://localhost:3000/api/users/68f445a8854f8ac2882fe422/logs?limit=1

### Get logs with query
GET http://localhost:3000/api/users/68f445a8854f8ac2882fe422/logs?from=2025-10-20

### Get logs with query
GET http://localhost:3000/api/users/68f445a8854f8ac2882fe422/logs?from=2025-10-1