### GET USERS -> returns all users
GET https://exercise-tracker.freecodecamp.rocks/api/users

### POST USER -> add a new user or returns it if exists
POST https://exercise-tracker.freecodecamp.rocks/api/users
Content-Type: application/json

{
    "username": "Camilo"
}

### GET USERS -> returns all users
GET https://exercise-tracker.freecodecamp.rocks/api/users

### POST EXERCISE
POST https://exercise-tracker.freecodecamp.rocks/api/users/67e394227673e60013e15487/exercises
Content-Type: application/json

{
    "description": "Jumping Jacks",
    "duration": 2
}

### POST EXERCISE user non existing
POST https://exercise-tracker.freecodecamp.rocks/api/users/a/exercises
Content-Type: application/json

{
    "description": "Jumping Jacks",
    "duration": 2
}

### POST EXERCISE with date
POST https://exercise-tracker.freecodecamp.rocks/api/users/67e394227673e60013e15487/exercises
Content-Type: application/json

{
    "description": "Jumping Jacks",
    "duration": 8,
    "date": "2025-08-28"
}

### POST EXERCISE with date
POST https://exercise-tracker.freecodecamp.rocks/api/users/67e394227673e60013e15487/exercises
Content-Type: application/json

{
    "description": "Soccer",
    "duration": 90,
    "date": "2025-08-26"
}

### POST EXERCISE with date
POST https://exercise-tracker.freecodecamp.rocks/api/users/67e394227673e60013e15487/exercises
Content-Type: application/json

{
    "description": "Basketball",
    "duration": 60,
    "date": "2023-08-26"
}

### GET ALL LOGS for c9517175-fa7a-4243-b7f8-8e04956ccd0e
GET https://exercise-tracker.freecodecamp.rocks/api/users/67e394227673e60013e15487/logs

### GET 2 LOGS for c9517175-fa7a-4243-b7f8-8e04956ccd0e from 01-01-2025 to 31-12-2025
GET https://exercise-tracker.freecodecamp.rocks/api/users/67e394227673e60013e15487/logs?from=2025-01-01&to=2025-12-31&limit=2
