### Add a user
POST https://joselriascos-exercise-tracker.netlify.app/api/users
Content-Type: application/json

{
    "username": "Jose"
}

### Add exercise
POST https://joselriascos-exercise-tracker.netlify.app/api/users/68f445a8854f8ac2882fe422/exercises
Content-Type: application/json

{
    "description": "algo",
    "duration": 5
}

### Add exercise with date
POST https://joselriascos-exercise-tracker.netlify.app/api/users/68f445a8854f8ac2882fe422/exercises
Content-Type: application/json

{
    "description": "otra cosa",
    "duration": 15,
    "date": "2025-08-28"
}

### Add user
POST https://joselriascos-exercise-tracker.netlify.app/api/users
Content-Type: application/json

{
    "username": "Diego"
}

### Add user
POST https://joselriascos-exercise-tracker.netlify.app/api/users
Content-Type: application/json

{
    "username": "Valen"
}

### Get users
GET https://joselriascos-exercise-tracker.netlify.app/api/users

### Get logs
GET https://joselriascos-exercise-tracker.netlify.app/api/users/68f445a8854f8ac2882fe422/logs

### Get logs with query
GET https://joselriascos-exercise-tracker.netlify.app/api/users/68f445a8854f8ac2882fe422/logs?limit=1

### Get logs with query
GET https://joselriascos-exercise-tracker.netlify.app/api/users/68f445a8854f8ac2882fe422/logs?from=2025-10-20

### Get logs with query
GET https://joselriascos-exercise-tracker.netlify.app/api/users/68f445a8854f8ac2882fe422/logs?from=2025-10-1